@startuml
skinparam linetype ortho
package adapters {
    package application {
        package model {
            package entity {
                class User {
                }
            }
        }
    }
}
adapters --> application
application --> model
model --> entity
model .[#red].> application
application .[#red].> entity
application .[#red].> User
application .[#red].> adapters
adapters .[#red].> model
adapters .[#red].> entity
adapters .[#red].> User
@enduml