@startuml
skinparam linetype ortho
package actor as actor {
}

package "Hexagonal Architecture" as hexa {
    package "Adapters" as adapters {
        package "Application" as aüü {
            package "Model" as model {
                class User {
                    +id: int
                    +name: String
                    +email: String
                }
            }
        }
    }
}

package "The Clean Architecture" as ca {
    package "Framework-Drivers" as fd {
        package "Interface-Adapters" as ia {
            package "Application-Business-Rules" as appRules {
                package "Enterprise-Business-Rules" as ebr {
                    class User {
                        +id: int
                        +username: String
                        +role: String
                    }
                }
            }
        }
    }
}

actor --> adapters
actor --> fd
adapters --> aüü
aüü --> model

fd --> ia
ia --> appRules
appRules --> ebr
@enduml
