package com.potucek.shop.drivers.drivers.web.rest.hawk;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

import static org.hamcrest.Matchers.containsString;
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
class RestHawkResourceCommandTest {

    public static final String PATH = "/hawks";

    @Autowired
    private MockMvc mvc;

    @Test
    public void hawks() throws Exception {
        mvc.perform(MockMvcRequestBuilders
                        .get(PATH)
                        .accept(APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().string(containsString("Greetings from Spring Boot!")));
    }

//    override fun then_() {
//        response
//      .body("size", equalTo(249))
//      .body("hawks[0].iucnCategory", equalTo("LC"))
//      .body("hawks[1].iucnCategory", equalTo("LC"))
//      .body("hawks[2].iucnCategory", equalTo("LC"))
//      .body("hawks[3].iucnCategory", equalTo("LC"))
//      .body("hawks[4].iucnCategory", equalTo("LC"))
//      .body("hawks[5].iucnCategory", equalTo("LC"))
//      .body("hawks[6].iucnCategory", equalTo("LC"))
//      .body("hawks[7].iucnCategory", equalTo("LC"))
//      .body("hawks[8].iucnCategory", equalTo("LC"))
//      .body("hawks[9].iucnCategory", equalTo("LC"))
//      .body("hawks[10].iucnCategory", equalTo("LC"))
//      .body("hawks[11].iucnCategory", equalTo("LC"))
//      .body("hawks[12].iucnCategory", equalTo("LC"))
//      .body("hawks[13].iucnCategory", equalTo("LC"))
//      .body("hawks[14].iucnCategory", equalTo("LC"))
//      .body("hawks[15].iucnCategory", equalTo("LC"))
//      .body("hawks[16].iucnCategory", equalTo("LC"))
//      .body("hawks[17].iucnCategory", equalTo("LC"))
//      .body("hawks[18].iucnCategory", equalTo("LC"))
//      .body("hawks[19].iucnCategory", equalTo("LC"))
//      .body("hawks[20].iucnCategory", equalTo("LC"))
//      .body("hawks[21].iucnCategory", equalTo("LC"))
//      .body("hawks[22].iucnCategory", equalTo("LC"))
//      .body("hawks[23].iucnCategory", equalTo("LC"))
//      .body("hawks[24].iucnCategory", equalTo("LC"))
//      .body("hawks[25].iucnCategory", equalTo("LC"))
//      .body("hawks[26].iucnCategory", equalTo("LC"))
//      .body("hawks[27].iucnCategory", equalTo("LC"))
//      .body("hawks[28].iucnCategory", equalTo("LC"))
//      .body("hawks[29].iucnCategory", equalTo("LC"))
//      .body("hawks[30].iucnCategory", equalTo("LC"))
//      .body("hawks[31].iucnCategory", equalTo("LC"))
//      .body("hawks[32].iucnCategory", equalTo("LC"))
//      .body("hawks[33].iucnCategory", equalTo("LC"))
//      .body("hawks[34].iucnCategory", equalTo("LC"))
//      .body("hawks[35].iucnCategory", equalTo("LC"))
//      .body("hawks[36].iucnCategory", equalTo("LC"))
//      .body("hawks[37].iucnCategory", equalTo("LC"))
//      .body("hawks[38].iucnCategory", equalTo("LC"))
//      .body("hawks[39].iucnCategory", equalTo("LC"))
//      .body("hawks[40].iucnCategory", equalTo("LC"))
//      .body("hawks[41].iucnCategory", equalTo("LC"))
//      .body("hawks[42].iucnCategory", equalTo("LC"))
//      .body("hawks[43].iucnCategory", equalTo("LC"))
//      .body("hawks[44].iucnCategory", equalTo("LC"))
//      .body("hawks[45].iucnCategory", equalTo("LC"))
//      .body("hawks[46].iucnCategory", equalTo("LC"))
//      .body("hawks[47].iucnCategory", equalTo("LC"))
//      .body("hawks[48].iucnCategory", equalTo("LC"))
//      .body("hawks[49].iucnCategory", equalTo("LC"))
//      .body("hawks[50].iucnCategory", equalTo("LC"))
//      .body("hawks[51].iucnCategory", equalTo("LC"))
//      .body("hawks[52].iucnCategory", equalTo("LC"))
//      .body("hawks[53].iucnCategory", equalTo("LC"))
//      .body("hawks[54].iucnCategory", equalTo("LC"))
//      .body("hawks[55].iucnCategory", equalTo("LC"))
//      .body("hawks[56].iucnCategory", equalTo("LC"))
//      .body("hawks[57].iucnCategory", equalTo("LC"))
//      .body("hawks[58].iucnCategory", equalTo("LC"))
//      .body("hawks[59].iucnCategory", equalTo("LC"))
//      .body("hawks[60].iucnCategory", equalTo("LC"))
//      .body("hawks[61].iucnCategory", equalTo("LC"))
//      .body("hawks[62].iucnCategory", equalTo("LC"))
//      .body("hawks[63].iucnCategory", equalTo("LC"))
//      .body("hawks[64].iucnCategory", equalTo("LC"))
//      .body("hawks[65].iucnCategory", equalTo("LC"))
//      .body("hawks[66].iucnCategory", equalTo("LC"))
//      .body("hawks[67].iucnCategory", equalTo("LC"))
//      .body("hawks[68].iucnCategory", equalTo("LC"))
//      .body("hawks[69].iucnCategory", equalTo("LC"))
//      .body("hawks[70].iucnCategory", equalTo("LC"))
//      .body("hawks[71].iucnCategory", equalTo("LC"))
//      .body("hawks[72].iucnCategory", equalTo("LC"))
//      .body("hawks[73].iucnCategory", equalTo("LC"))
//      .body("hawks[74].iucnCategory", equalTo("LC"))
//      .body("hawks[75].iucnCategory", equalTo("LC"))
//      .body("hawks[76].iucnCategory", equalTo("LC"))
//      .body("hawks[77].iucnCategory", equalTo("LC"))
//      .body("hawks[78].iucnCategory", equalTo("LC"))
//      .body("hawks[79].iucnCategory", equalTo("LC"))
//      .body("hawks[80].iucnCategory", equalTo("LC"))
//      .body("hawks[81].iucnCategory", equalTo("LC"))
//      .body("hawks[82].iucnCategory", equalTo("LC"))
//      .body("hawks[83].iucnCategory", equalTo("LC"))
//      .body("hawks[84].iucnCategory", equalTo("LC"))
//      .body("hawks[85].iucnCategory", equalTo("LC"))
//      .body("hawks[86].iucnCategory", equalTo("LC"))
//      .body("hawks[87].iucnCategory", equalTo("LC"))
//      .body("hawks[88].iucnCategory", equalTo("LC"))
//      .body("hawks[89].iucnCategory", equalTo("LC"))
//      .body("hawks[90].iucnCategory", equalTo("LC"))
//      .body("hawks[91].iucnCategory", equalTo("LC"))
//      .body("hawks[92].iucnCategory", equalTo("LC"))
//      .body("hawks[93].iucnCategory", equalTo("LC"))
//      .body("hawks[94].iucnCategory", equalTo("LC"))
//      .body("hawks[95].iucnCategory", equalTo("LC"))
//      .body("hawks[96].iucnCategory", equalTo("LC"))
//      .body("hawks[97].iucnCategory", equalTo("LC"))
//      .body("hawks[98].iucnCategory", equalTo("LC"))
//      .body("hawks[99].iucnCategory", equalTo("LC"))
//      .body("hawks[100].iucnCategory", equalTo("LC"))
//      .body("hawks[101].iucnCategory", equalTo("LC"))
//      .body("hawks[102].iucnCategory", equalTo("LC"))
//      .body("hawks[103].iucnCategory", equalTo("LC"))
//      .body("hawks[104].iucnCategory", equalTo("LC"))
//      .body("hawks[105].iucnCategory", equalTo("LC"))
//      .body("hawks[106].iucnCategory", equalTo("LC"))
//      .body("hawks[107].iucnCategory", equalTo("LC"))
//      .body("hawks[108].iucnCategory", equalTo("LC"))
//      .body("hawks[109].iucnCategory", equalTo("LC"))
//      .body("hawks[110].iucnCategory", equalTo("LC"))
//      .body("hawks[111].iucnCategory", equalTo("LC"))
//      .body("hawks[112].iucnCategory", equalTo("LC"))
//      .body("hawks[113].iucnCategory", equalTo("LC"))
//      .body("hawks[114].iucnCategory", equalTo("LC"))
//      .body("hawks[115].iucnCategory", equalTo("LC"))
//      .body("hawks[116].iucnCategory", equalTo("LC"))
//      .body("hawks[117].iucnCategory", equalTo("LC"))
//      .body("hawks[118].iucnCategory", equalTo("LC"))
//      .body("hawks[119].iucnCategory", equalTo("LC"))
//      .body("hawks[120].iucnCategory", equalTo("LC"))
//      .body("hawks[121].iucnCategory", equalTo("LC"))
//      .body("hawks[122].iucnCategory", equalTo("LC"))
//      .body("hawks[123].iucnCategory", equalTo("LC"))
//      .body("hawks[124].iucnCategory", equalTo("LC"))
//      .body("hawks[125].iucnCategory", equalTo("LC"))
//      .body("hawks[126].iucnCategory", equalTo("LC"))
//      .body("hawks[127].iucnCategory", equalTo("LC"))
//      .body("hawks[128].iucnCategory", equalTo("LC"))
//      .body("hawks[129].iucnCategory", equalTo("LC"))
//      .body("hawks[130].iucnCategory", equalTo("LC"))
//      .body("hawks[131].iucnCategory", equalTo("LC"))
//      .body("hawks[132].iucnCategory", equalTo("LC"))
//      .body("hawks[133].iucnCategory", equalTo("LC"))
//      .body("hawks[134].iucnCategory", equalTo("LC"))
//      .body("hawks[135].iucnCategory", equalTo("LC"))
//      .body("hawks[136].iucnCategory", equalTo("LC"))
//      .body("hawks[137].iucnCategory", equalTo("LC"))
//      .body("hawks[138].iucnCategory", equalTo("LC"))
//      .body("hawks[139].iucnCategory", equalTo("LC"))
//      .body("hawks[140].iucnCategory", equalTo("LC"))
//      .body("hawks[141].iucnCategory", equalTo("LC"))
//      .body("hawks[142].iucnCategory", equalTo("LC"))
//      .body("hawks[143].iucnCategory", equalTo("LC"))
//      .body("hawks[144].iucnCategory", equalTo("LC"))
//      .body("hawks[145].iucnCategory", equalTo("LC"))
//      .body("hawks[146].iucnCategory", equalTo("LC"))
//      .body("hawks[147].iucnCategory", equalTo("LC"))
//      .body("hawks[148].iucnCategory", equalTo("LC"))
//      .body("hawks[149].iucnCategory", equalTo("LC"))
//      .body("hawks[150].iucnCategory", equalTo("LC"))
//      .body("hawks[151].iucnCategory", equalTo("LC"))
//      .body("hawks[152].iucnCategory", equalTo("LC"))
//      .body("hawks[153].iucnCategory", equalTo("LC"))
//      .body("hawks[154].iucnCategory", equalTo("LC"))
//      .body("hawks[155].iucnCategory", equalTo("LC"))
//      .body("hawks[156].iucnCategory", equalTo("LC"))
//      .body("hawks[157].iucnCategory", equalTo("LC"))
//      .body("hawks[158].iucnCategory", equalTo("LC"))
//      .body("hawks[159].iucnCategory", equalTo("NT"))
//      .body("hawks[160].iucnCategory", equalTo("NT"))
//      .body("hawks[161].iucnCategory", equalTo("NT"))
//      .body("hawks[162].iucnCategory", equalTo("NT"))
//      .body("hawks[163].iucnCategory", equalTo("NT"))
//      .body("hawks[164].iucnCategory", equalTo("NT"))
//      .body("hawks[165].iucnCategory", equalTo("NT"))
//      .body("hawks[166].iucnCategory", equalTo("NT"))
//      .body("hawks[167].iucnCategory", equalTo("NT"))
//      .body("hawks[168].iucnCategory", equalTo("NT"))
//      .body("hawks[169].iucnCategory", equalTo("NT"))
//      .body("hawks[170].iucnCategory", equalTo("NT"))
//      .body("hawks[171].iucnCategory", equalTo("NT"))
//      .body("hawks[172].iucnCategory", equalTo("NT"))
//      .body("hawks[173].iucnCategory", equalTo("NT"))
//      .body("hawks[174].iucnCategory", equalTo("NT"))
//      .body("hawks[175].iucnCategory", equalTo("NT"))
//      .body("hawks[176].iucnCategory", equalTo("NT"))
//      .body("hawks[177].iucnCategory", equalTo("NT"))
//      .body("hawks[178].iucnCategory", equalTo("NT"))
//      .body("hawks[179].iucnCategory", equalTo("NT"))
//      .body("hawks[180].iucnCategory", equalTo("NT"))
//      .body("hawks[181].iucnCategory", equalTo("NT"))
//      .body("hawks[182].iucnCategory", equalTo("NT"))
//      .body("hawks[183].iucnCategory", equalTo("NT"))
//      .body("hawks[184].iucnCategory", equalTo("NT"))
//      .body("hawks[185].iucnCategory", equalTo("NT"))
//      .body("hawks[186].iucnCategory", equalTo("NT"))
//      .body("hawks[187].iucnCategory", equalTo("NT"))
//      .body("hawks[188].iucnCategory", equalTo("NT"))
//      .body("hawks[189].iucnCategory", equalTo("NT"))
//      .body("hawks[190].iucnCategory", equalTo("NT"))
//      .body("hawks[191].iucnCategory", equalTo("NT"))
//      .body("hawks[192].iucnCategory", equalTo("NT"))
//      .body("hawks[193].iucnCategory", equalTo("VU"))
//      .body("hawks[194].iucnCategory", equalTo("VU"))
//      .body("hawks[195].iucnCategory", equalTo("VU"))
//      .body("hawks[196].iucnCategory", equalTo("VU"))
//      .body("hawks[197].iucnCategory", equalTo("VU"))
//      .body("hawks[198].iucnCategory", equalTo("VU"))
//      .body("hawks[199].iucnCategory", equalTo("VU"))
//      .body("hawks[200].iucnCategory", equalTo("VU"))
//      .body("hawks[201].iucnCategory", equalTo("VU"))
//      .body("hawks[202].iucnCategory", equalTo("VU"))
//      .body("hawks[203].iucnCategory", equalTo("VU"))
//      .body("hawks[204].iucnCategory", equalTo("VU"))
//      .body("hawks[205].iucnCategory", equalTo("VU"))
//      .body("hawks[206].iucnCategory", equalTo("VU"))
//      .body("hawks[207].iucnCategory", equalTo("VU"))
//      .body("hawks[208].iucnCategory", equalTo("VU"))
//      .body("hawks[209].iucnCategory", equalTo("VU"))
//      .body("hawks[210].iucnCategory", equalTo("VU"))
//      .body("hawks[211].iucnCategory", equalTo("VU"))
//      .body("hawks[212].iucnCategory", equalTo("VU"))
//      .body("hawks[213].iucnCategory", equalTo("VU"))
//      .body("hawks[214].iucnCategory", equalTo("VU"))
//      .body("hawks[215].iucnCategory", equalTo("VU"))
//      .body("hawks[216].iucnCategory", equalTo("VU"))
//      .body("hawks[217].iucnCategory", equalTo("EN"))
//      .body("hawks[218].iucnCategory", equalTo("EN"))
//      .body("hawks[219].iucnCategory", equalTo("EN"))
//      .body("hawks[220].iucnCategory", equalTo("EN"))
//      .body("hawks[221].iucnCategory", equalTo("EN"))
//      .body("hawks[222].iucnCategory", equalTo("EN"))
//      .body("hawks[223].iucnCategory", equalTo("EN"))
//      .body("hawks[224].iucnCategory", equalTo("EN"))
//      .body("hawks[225].iucnCategory", equalTo("EN"))
//      .body("hawks[226].iucnCategory", equalTo("EN"))
//      .body("hawks[227].iucnCategory", equalTo("EN"))
//      .body("hawks[228].iucnCategory", equalTo("EN"))
//      .body("hawks[229].iucnCategory", equalTo("EN"))
//      .body("hawks[230].iucnCategory", equalTo("EN"))
//      .body("hawks[231].iucnCategory", equalTo("EN"))
//      .body("hawks[232].iucnCategory", equalTo("EN"))
//      .body("hawks[233].iucnCategory", equalTo("EN"))
//      .body("hawks[234].iucnCategory", equalTo("CR"))
//      .body("hawks[235].iucnCategory", equalTo("CR"))
//      .body("hawks[236].iucnCategory", equalTo("CR"))
//      .body("hawks[237].iucnCategory", equalTo("CR"))
//      .body("hawks[238].iucnCategory", equalTo("CR"))
//      .body("hawks[239].iucnCategory", equalTo("CR"))
//      .body("hawks[240].iucnCategory", equalTo("CR"))
//      .body("hawks[241].iucnCategory", equalTo("CR"))
//      .body("hawks[242].iucnCategory", equalTo("CR"))
//      .body("hawks[243].iucnCategory", equalTo("CR"))
//      .body("hawks[244].iucnCategory", equalTo("CR"))
//      .body("hawks[245].iucnCategory", equalTo("CR"))
//      .body("hawks[246].iucnCategory", equalTo("CR"))
//      .body("hawks[247].iucnCategory", equalTo("EX"))
//      .body("hawks[248].iucnCategory", equalTo("DD"))
//    }

}